module.export = {
  SKILL_NAME: 'Driving Test',
  WELCOME_MESSAGE: '¡Welcome to Driving Test! I\'m going to ask you questions to practice the Spanish driving license exam. The questions have been obtained from the DGT website in 2018. Please answer the questions saying A, B, C... Let\'s start!',
  WELCOME_REPROMPT: 'Answer the questions saying A, B, C... To get help, please say "help". To leave, just say "stop".',
  HELP_MESSAGE: 'I\'m going to ask you questions to practice the Spanish driving license exam. The questions have been obtained from the DGT website in 2018. Please answer the questions saying A, B or C. To listen to it again, say "repeat". You can also say "stop", "next" or "stats". What is your response?',
  STOP_MESSAGE: 'Bye!',
  NO_ENTIENDO_REPITE_POR_FAVOR: 'I\'m sorry, I don\'t understand you. Repeat please.',
  NEXT_QUESTION: 'Next question: ',
  LA_PREGUNTA: 'The question: ',
  QUE_LETRA_ELIGES: 'What letter do you choose?',
  ESTA_MAL: 'is wrong',
  RESPUESTA_CORRECTA: 'Correct answer!',
  RESPUESTA_INCORRECTA: 'Wrong answer',
  VUELVE_A_INTENTARLO: 'Try again',
  REPITO_LA_PREGUNTA: 'I repeat the question: ',
  NO_EXISTE_EN_ESTA_PREGUNTA: "doesn't exist for this question",
  HINT_TEXT: 'Try "letter A", "letter B", "letter C", "repeat", "next", "stats" or "stop"',
  ENUNCIADO_HELP: 'I\'m going to ask you questions to practice the Spanish driving license exam. The questions have been obtained from the DGT website in 2018. Please answer the questions saying A, B or C. To listen to it again, say "repeat". You can also say "stop", "next" or "stats". What is your response?',
  OTRAS_SKILLS: 'Other recommended skills that you can enable in your Alexa (in Spanish):',
  TUS_STATS: 'Your statistics for this session are here.',
  DI_ATRAS_PARA_VOLVER: "Say 'back' to return.",
  HINT_VOLVER: 'Say "back"',
  STATS_LEYENDA_1: 'Total questions answered',
  STATS_LEYENDA_2: 'Correct answers',
  STATS_LEYENDA_3: 'Failed answers',
  ALERTA_PREGUNTA: 'You failed this question the last time',
  LETRA: '',
};
