module.exports = {
  SKILL_NAME: 'Test Autoescuela',
  WELCOME_MESSAGE: '¡Bienvenido a Test Autoescuela! Voy a hacerte preguntas para que practiques el examen de permiso B de conducir. Las preguntas se han extraído de la web de la DGT en 2018. Contesta a las preguntas diciendo A, B, C... ¡Empezamos!',
  WELCOME_REPROMPT: 'Contesta a las preguntas diciendo A, B, C... Para recibir ayuda, por favor di ayuda. Para salir, di salir.',
  HELP_MESSAGE: 'Voy a hacerte preguntas para que practiques el examen de permiso B de conducir. Las preguntas se han extraído de la web de la DGT en 2018. Contesta a la última pregunta diciendo A,B o C. Para volver a escucharla, di "repetir". También puedes decir "salir", "estadísticas" o "siguiente". ¿Qué respondes?',
  STOP_MESSAGE: '<say-as interpret-as="interjection">Hasta luego</say-as>',
  NO_ENTIENDO_REPITE_POR_FAVOR: '<say-as interpret-as="interjection">¿cómorr?</say-as>. Lo siento, no te he entendido. Repite por favor.',
  NEXT_QUESTION: 'Siguiente pregunta: ',
  LA_PREGUNTA: 'La pregunta: ',
  QUE_LETRA_ELIGES: '¿Qué letra eliges?',
  ESTA_MAL: 'no es',
  RESPUESTA_CORRECTA: '¡Respuesta correcta!',
  RESPUESTA_INCORRECTA: 'Respuesta incorrecta',
  VUELVE_A_INTENTARLO: 'Vuelve a intentarlo',
  REPITO_LA_PREGUNTA: 'Repito la pregunta: ',
  NO_EXISTE_EN_ESTA_PREGUNTA: 'no existe en esta pregunta',
  HINT_TEXT: 'Di "A", "B", "C", "repetir", "siguiente", "estadísticas" o "salir"',
  ENUNCIADO_HELP: 'Esta skill hace preguntas para que practiques el examen de permiso B de conducir de España. Las preguntas se han extraído de la web de la DGT en 2018. Contesta a la última pregunta diciendo A,B o C. Para volver a escucharla, di "repetir". También puedes decir "salir" o "siguiente". ¿Qué respondes?',
  OTRAS_SKILLS: 'Otras skills recomendadas que puedes habilitar en tu Alexa (en español):',
  TUS_STATS: 'Aquí están tus estadísticas de esta partida.',
  DI_ATRAS_PARA_VOLVER: 'Di volver para continuar.',
  HINT_VOLVER: 'Di "volver"',
  STATS_LEYENDA_1: 'Total preguntas contestadas',
  STATS_LEYENDA_2: 'Preguntas acertadas',
  STATS_LEYENDA_3: 'Preguntas falladas',
  ALERTA_PREGUNTA: 'Fallaste esta pregunta la última vez',
  LETRA: '',
};
